// #### AUTO-GENERATED CODE ####
// Please avoid editing
// Copyright © Brisk Technologies

namespace Brisk.Actions {
    public sealed class AutoGenerated_BriskActionSet : Brisk.Actions.ActionSet {
        private readonly System.Collections.Generic.Dictionary<int, System.Action<Brisk.Entities.NetBehaviour, Lidgren.Network.NetIncomingMessage>> actions =
            new System.Collections.Generic.Dictionary<int, System.Action<Brisk.Entities.NetBehaviour, Lidgren.Network.NetIncomingMessage>> {
                {0, (bhr, msg) => {
                    ((Brisk.Entities.NetEntity)bhr).Destroy();
                }},
        };

        public override void Call(Brisk.Entities.NetEntity entity, byte behaviourId, Lidgren.Network.NetIncomingMessage msg, int actionId) {
            if (actions.TryGetValue(actionId, out var action)) action(entity.Behaviour(behaviourId), msg);
            else UnityEngine.Debug.LogError($"Action not found with ID: {actionId}");
        }
    }
    public static class AutoGenerated_BriskActionExtensions {
        public static void Net_Destroy(this Brisk.Entities.NetEntity bhr) {
            bhr.Entity.Peer.Messages.ActionLocal(0, bhr.Entity.Entity.Id, bhr.Entity.Entity.Behaviour(bhr));
        }
    }
}
